### ISSUE TITLE
cftime.DatetimeNoLeap issue

### ISSUE THREAD

**Issue by MatProv** [bird-house/finch#122]
## Description

Having this log in finch, in prod (pavics.climatedata.ca).
Related to cftime.DatetimeNoLeap issue.

```
2020-04-06T21:49:53.662956178Z Traceback (most recent call last):
2020-04-06T21:49:53.662984798Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4844, in get_slice_bound
2020-04-06T21:49:53.662989470Z     return self._searchsorted_monotonic(label, side)
2020-04-06T21:49:53.662992951Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4805, in _searchsorted_monotonic
2020-04-06T21:49:53.662996380Z     raise ValueError("index must be monotonic increasing or decreasing")
2020-04-06T21:49:53.662999780Z ValueError: index must be monotonic increasing or decreasing
2020-04-06T21:49:53.663002947Z 
2020-04-06T21:49:53.663006124Z During handling of the above exception, another exception occurred:
2020-04-06T21:49:53.663009268Z 
2020-04-06T21:49:53.663021940Z Traceback (most recent call last):
2020-04-06T21:49:53.663024981Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pywps/app/Process.py", line 243, in _run_process
2020-04-06T21:49:53.663027949Z     self.handler(wps_request, wps_response)  # the user must update the wps_response.
2020-04-06T21:49:53.663030766Z   File "/code/finch/processes/wps_base.py", line 36, in _handler_wrapper
2020-04-06T21:49:53.663033646Z     return self.wrapped_handler(request, response)
2020-04-06T21:49:53.663036415Z   File "/code/finch/processes/wps_ensemble_indices_point.py", line 76, in _handler
2020-04-06T21:49:53.663039298Z     return ensemble_common_handler(self, request, response, finch_subset_gridpoint)
2020-04-06T21:49:53.663042092Z   File "/code/finch/processes/ensemble_utils.py", line 528, in ensemble_common_handler
2020-04-06T21:49:53.663044966Z     subsetted_files = subset_function(
2020-04-06T21:49:53.663047672Z   File "/code/finch/processes/subset.py", line 102, in finch_subset_gridpoint
2020-04-06T21:49:53.663050571Z     process_threaded(_subset, netcdf_inputs)
2020-04-06T21:49:53.663053294Z   File "/code/finch/processes/utils.py", line 274, in process_threaded
2020-04-06T21:49:53.663056133Z     outputs = [function(r) for r in inputs]
2020-04-06T21:49:53.663058870Z   File "/code/finch/processes/utils.py", line 274, in <listcomp>
2020-04-06T21:49:53.663062060Z     outputs = [function(r) for r in inputs]
2020-04-06T21:49:53.663064792Z   File "/code/finch/processes/subset.py", line 80, in _subset
2020-04-06T21:49:53.663067674Z     subset = subset_gridpoint(
2020-04-06T21:49:53.663070397Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 208, in func_checker
2020-04-06T21:49:53.663073288Z     final = func(*formatted_args, **kwargs)
2020-04-06T21:49:53.663076001Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 164, in func_checker
2020-04-06T21:49:53.663078851Z     return func(*args, **kwargs)
2020-04-06T21:49:53.663081605Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 63, in func_checker
2020-04-06T21:49:53.663084475Z     return func(*args, **kwargs)
2020-04-06T21:49:53.663088015Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 852, in subset_gridpoint
2020-04-06T21:49:53.663091000Z     da = subset_time(da, start_date=start_date, end_date=end_date)
2020-04-06T21:49:53.663093897Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 121, in func_checker
2020-04-06T21:49:53.663096742Z     return func(*args, **kwargs)
2020-04-06T21:49:53.663099412Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xclim/subset.py", line 906, in subset_time
2020-04-06T21:49:53.663102601Z     return da.sel(time=slice(start_date, end_date))
2020-04-06T21:49:53.663105509Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/dataset.py", line 2056, in sel
2020-04-06T21:49:53.663110788Z     pos_indexers, new_indexes = remap_label_indexers(
2020-04-06T21:49:53.663113702Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/coordinates.py", line 391, in remap_label_indexers
2020-04-06T21:49:53.663116681Z     pos_indexers, new_indexes = indexing.remap_label_indexers(
2020-04-06T21:49:53.663119409Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 270, in remap_label_indexers
2020-04-06T21:49:53.663122302Z     idxr, new_idx = convert_label_indexer(index, label, dim, method, tolerance)
2020-04-06T21:49:53.663125083Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/core/indexing.py", line 121, in convert_label_indexer
2020-04-06T21:49:53.663127999Z     indexer = index.slice_indexer(
2020-04-06T21:49:53.663130679Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4712, in slice_indexer
2020-04-06T21:49:53.663133578Z     start_slice, end_slice = self.slice_locs(start, end, step=step, kind=kind)
2020-04-06T21:49:53.663136322Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4925, in slice_locs
2020-04-06T21:49:53.663139195Z     start_slice = self.get_slice_bound(start, "left", kind)
2020-04-06T21:49:53.663142028Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4847, in get_slice_bound
2020-04-06T21:49:53.663144994Z     raise err
2020-04-06T21:49:53.663147668Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 4841, in get_slice_bound
2020-04-06T21:49:53.663150558Z     slc = self.get_loc(label)
2020-04-06T21:49:53.663153248Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/xarray/coding/cftimeindex.py", line 334, in get_loc
2020-04-06T21:49:53.663156115Z     return pd.Index.get_loc(self, key, method=method, tolerance=tolerance)
2020-04-06T21:49:53.663159208Z   File "/opt/conda/envs/finch/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
2020-04-06T21:49:53.663162107Z     return self._engine.get_loc(self._maybe_cast_indexer(key))
2020-04-06T21:49:53.663164872Z   File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
2020-04-06T21:49:53.663167719Z   File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
2020-04-06T21:49:53.663170547Z   File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
2020-04-06T21:49:53.663173434Z   File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
2020-04-06T21:49:53.663176362Z KeyError: cftime.DatetimeNoLeap(1950-01-01 00:00:00)
2020-04-06T21:49:53.663179147Z ERROR:PYWPS:Process error: method=wps_ensemble_indices_point.py._handler, line=76, msg=cftime.DatetimeNoLeap(1950-01-01 00:00:00)
```

## Environment

* finch version used, if any: 0.5.1
* Python version, if any: 3.8
* Operating System: Centos 7 (prod environment)

## Steps to Reproduce

POST ``/processes/ensemble_grid_point_cooling_degree_days/jobs``
```
{
	"inputs": [
		{
			"id": "lat",
			"data": "50.440716495074405"
		},
		{
			"id": "lon",
			"data": "-104.7148707386028"
		},
		{
			"id": "start_date",
			"data": "1955"
		},
		{
			"id": "end_date",
			"data": "2010"
		},
		{
			"id": "ensemble_percentiles",
			"data": "10,50,90"
		},
		{
			"id": "dataset_name",
			"data": "bccaqv2"
		},
		{
			"id": "rcp",
			"data": "rcp85"
		},
		{
			"id": "models",
			"data": "24MODELS"
		},
		{
			"id": "freq",
			"data": "YS"
		},
		{
			"id": "output_format",
			"data": "csv"
		},
		{
			"id": "thresh",
			"data": "18 degC"
		}
	],
	"response": "document",
	"mode": "auto",
	"outputs": [
		{
			"transmissionMode": "reference",
			"id": "output"
		}
	]
}
```

will output error ``cftime.DatetimeNoLeap(1955-01-01 00:00:00)``

## Additional Information

- Important :  Error usually occurs during 
  - ``INFO:PYWPS:Subsetting file 46 of 48`` on finch.crim.ca (dev)
  - ``INFO:PYWPS:Subsetting file 13 of 48`` on pavics.climatedata.ca (prod)
Both files being processed refers to "tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc"

- Related to #97 
- Maybe related to recent changes in xarray. See https://stackoverflow.com/questions/54462798/cftime-datetimenoleap-object-fails-to-convert-with-pandas-to-datetime

**Comment by MatProv** [comment]
``tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc`` has 'time' issue. Will be fixed on Boreas with the time of rcp45 (which is fine) and be synced on prod.
