### ISSUE TITLE
InvalidParameterValue wps issue

### ISSUE THREAD

**Issue by MatProv** [bird-house/finch#123]
## Description

Having this log in finch, in prod (pavics.climatedata.ca).
Related to InvalidParameterValue.

```
2020-04-06T12:04:16.578172896Z [2020-04-06 12:04:16,575] ERROR    [MainThread][weaver.wps_restapi.processes.processes] Failed running [Job <f684c9b5-ba8e-4e42-92e6-cf81b995c78e>]
2020-04-06T12:04:16.578189068Z Traceback (most recent call last):
2020-04-06T12:04:16.578193213Z   File "/opt/local/src/weaver/weaver/wps_restapi/processes/processes.py", line 145, in execute_process
2020-04-06T12:04:16.578196458Z     execution = wps.execute(job.process, inputs=wps_inputs, output=outputs, mode=mode, lineage=True)
2020-04-06T12:04:16.578199628Z   File "/usr/local/lib/python3.7/site-packages/owslib/wps.py", line 359, in execute
2020-04-06T12:04:16.578202746Z     response = execution.submitRequest(request)
2020-04-06T12:04:16.578205747Z   File "/usr/local/lib/python3.7/site-packages/owslib/wps.py", line 906, in submitRequest
2020-04-06T12:04:16.578209086Z     self.url, request, method='Post', headers=self.headers)
2020-04-06T12:04:16.578211998Z   File "/usr/local/lib/python3.7/site-packages/owslib/wps.py", line 603, in readFromUrl
2020-04-06T12:04:16.578214904Z     headers=headers, verify=verify, cert=cert)
2020-04-06T12:04:16.578217745Z   File "/usr/local/lib/python3.7/site-packages/owslib/wps.py", line 515, in _readFromUrl
2020-04-06T12:04:16.578220646Z     headers=headers, verify=self.auth.verify, cert=self.auth.cert, timeout=timeout)
2020-04-06T12:04:16.578223510Z   File "/usr/local/lib/python3.7/site-packages/owslib/util.py", line 207, in openURL
2020-04-06T12:04:16.578226568Z     raise ServiceException(req.text)
2020-04-06T12:04:16.578229543Z owslib.util.ServiceException: <?xml version="1.0" encoding="UTF-8"?>
2020-04-06T12:04:16.578232771Z <!-- PyWPS 4.2.2 -->
2020-04-06T12:04:16.578235758Z <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
2020-04-06T12:04:16.578239361Z   <ows:Exception exceptionCode="InvalidParameterValue" locator="" >
2020-04-06T12:04:16.578242390Z       <ows:ExceptionText>Input data not valid using mode 1</ows:ExceptionText>
2020-04-06T12:04:16.578245523Z   </ows:Exception>
2020-04-06T12:04:16.578256779Z </ows:ExceptionReport>
2020-04-06T12:04:16.578338970Z [2020-04-06 12:04:16,578] ERROR    [MainThread][weaver.wps_restapi.processes.processes] 0:00:01  80% failed     Failed to run Job <f684c9b5-ba8e-4e42-92e6-cf81b995c78e>.
2020-04-06T12:04:16.578536512Z [2020-04-06 12:04:16,578] INFO     [MainThread][weaver.wps_restapi.processes.processes] 0:00:01  90% failed     Job failed.
2020-04-06T12:04:16.621661630Z [2020-04-06 12:04:16,621] INFO     [MainThread][weaver.wps_restapi.processes.processes] 0:00:01  95% failed     Notification email sent successfully.
2020-04-06T12:04:16.621764621Z [2020-04-06 12:04:16,621] INFO     [MainThread][weaver.wps_restapi.processes.processes] 0:00:01 100% failed     Job task complete.
```

In finch:
```
2020-04-06T12:04:16.532476133Z INFO:PYWPS:Request: execute
2020-04-06T12:04:16.544049698Z ERROR:PYWPS:Exception: code: 400, description: Input data not valid using mode 1, locator: 
2020-04-06T12:04:16.544063138Z NoneType: None
```

## Environment

* finch version used, if any: 0.5.1
* Python version, if any: 3.8
* Operating System: Centos 7 (prod environment)

## Steps to Reproduce

Seems to be any request maybe using multiple RCPs. 
Happen in other circumstances as well.

## Additional Information

none

**Comment by MatProv** [comment]
Closing this issue as multiple RCPs/freq is in fact not supported for now.
This issue will be reopened if it this issue happens on valid inputs.
