### ISSUE TITLE
subset_bbox_dataset fails with output_format=csv

### ISSUE THREAD

**Issue by perronld** [bird-house/finch#251]
## Description   (updated: changed Finch version from 0.9.1 to 0.9.2)

subset_bbox_dataset fails with output_format=csv

## Environment

* Finch version used, if any: 0.9.2
* Operating System: finch docker image version-0.9.2

## Steps to Reproduce

Run subset_bbox_dataset on the bccaqv2 dataset with output_format='csv'.   Note: bounding box must be small, otherwise it will fail with OOM.

```
Traceback (most recent call last):
  File "/code/finch/processes/wps_base.py", line 43, in _handler_wrapper
    resp = self.wrapped_handler(request, response)
  File "/code/finch/processes/wps_xsubset_bbox_dataset.py", line 94, in _handler
    csv_files, metadata_folder = netcdf_file_list_to_csv(
  File "/code/finch/processes/utils.py", line 489, in netcdf_file_list_to_csv
    concat = pd.concat(data, axis=1)
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 360, in concat
    return op.get_result()
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 591, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
Traceback (most recent call last):
  File "/code/finch/processes/wps_base.py", line 43, in _handler_wrapper
    resp = self.wrapped_handler(request, response)
  File "/code/finch/processes/wps_xsubset_bbox_dataset.py", line 94, in _handler
    csv_files, metadata_folder = netcdf_file_list_to_csv(
  File "/code/finch/processes/utils.py", line 489, in netcdf_file_list_to_csv
    concat = pd.concat(data, axis=1)
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 360, in concat
    return op.get_result()
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 591, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/finch/lib/python3.10/site-packages/pywps/app/Process.py", line 250, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/code/finch/processes/wps_base.py", line 48, in _handler_wrapper
    raise ProcessError(f"Finch failed with {err!r}")
pywps.app.exceptions.ProcessError: Finch failed with InvalidIndexError Reindexing only valid with uniquely valued Index objects

```

**Comment by tlvu** [comment]
FYI there is a new Finch 0.9.2 docker image without numpy downgrade, and that starts properly without error that needed numpy downgrade.
