### ISSUE TITLE
Fix segmentation fault in Travis ci test suite

### ISSUE THREAD

**Issue by davidcaron** [bird-house/finch#54]
## Description

Travis CI fails with a segmentation fault.

## Environment

* Finch version used, if any: latest
* Python version, if any: 3.6
* Operating System: Linux

## Steps to Reproduce

The test responsible for the segmentation fault is: `tests/test_wps_xsubsetpoint.py::test_thredds`.

I could reproduce the error with this very simplified piece of code:

```python
import xarray as xr
from pathlib import Path

here = Path(__file__).parent

url1 = "http://test.opendap.org:8080/opendap/netcdf/examples/tos_O1_2001-2002.nc"
url2 = "http://test.opendap.org:8080/opendap/netcdf/examples/sresa1b_ncar_ccsm3_0_run1_200001.nc"

for n, url in enumerate([url2, url1]):
    ds = xr.open_dataset(url)
    ds.to_netcdf(str(here / f'{n}.nc'))
```

Notice how no part of finch or pywps is touched in this code. The error we get is either:

```
1]    22220 segmentation fault (core dumped)  env USER=ubuntu  SHLVL=0 HOME=/home/ubuntu  LOGNAME=ubuntu NAME=###my_hostname###
```

Or when we use opendap files from pavics.ouranos.ca, we actually get a traceback:

```
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 240, in __del__
    self.close(needs_lock=False)
  File "/home/ubuntu/miniconda3/envs/finch/lib/python3.6/site-packages/xarray/backends/file_manager.py", line 218, in close
    file.close()
  File "netCDF4/_netCDF4.pyx", line 2485, in netCDF4._netCDF4.Dataset.close
  File "netCDF4/_netCDF4.pyx", line 2449, in netCDF4._netCDF4.Dataset._close
  File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: cannot delete file
python: /home/conda/feedstock_root/build_artifacts/libnetcdf_1574519229483/work/libdap2/dceconstraints.c:512: dcefree: Assertion `0' failed.
```

## Additional Information

I will try to simplify the python environment in which I encounter this issue to see if I can isolate a particular library, and keep this issue updated of my findings.

**Comment by davidcaron** [comment]
And here is the conda environment to reproduce this bug:

```
name: finch-bug 
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py38_0
  - cftime=1.0.4.2=py38hc1659b7_0
  - curl=7.65.3=hf8cf82a_0
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - jpeg=9c=h14c3975_1001
  - krb5=1.16.3=h05b26f9_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=hda55be3_0 
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_2
  - liblapack=3.8.0=14_openblas
  - libnetcdf=4.7.1=nompi_h94020b1_102
  - libopenblas=0.3.7=h5ec1e0e_4
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_0
  - ncurses=6.1=hf484d3e_1002
  - netcdf4=1.5.3=nompi_py38hfee4bf2_101
  - numpy=1.17.3=py38h95a1406_0
  - openssl=1.1.1d=h516909a_0
  - pandas=0.25.3=py38hb3f55d8_0
  - pip=19.3.1=py38_0
  - python=3.8.0=h357f687_5 
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - readline=8.0=hf8c457e_0
  - setuptools=42.0.2=py38_0
  - six=1.13.0=py38_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - wheel=0.33.6=py38_0
  - xarray=0.14.1=py_0 
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
```
which I created by installing only xarray and netCDF4 from conda-forge.

**Comment by davidcaron** [comment]
There seems to be no problem when using pydap as the engine: `ds = xr.open_dataset(url, engine='pydap')`

**Comment by davidcaron** [comment]
For reference, there is a related issue in the netcdf4-python repo: https://github.com/Unidata/netcdf4-python/issues/982
